[package]
name = "VivOS"
version = "0.1.1"
edition = "2024"

[dependencies]
uefi = "0.36.1"
uefi-services = "0.26.0"

[profile.release]
panic = "abort"
lto = true
strip = true
opt-level = 2
codegen-units = 1

[[bin]]
name = "bootloader"
path = "src/boot.rs"
