[package]
name = "VivOS"
version = "0.1.1"
edition = "2024"

[dependencies]
uefi = "0.36.1"
efi = "0.3.1"
ffi = "0.1.1"

[profile.release]
panic = "abort"
lto = true
strip = true
opt-level = 2
codegen-units = 1
debug = false

[[bin]]
name = "bootloader"
path = "bootloader/src/main.rs"
